export const ROUTES = {
  home: "/",
  adminLogin: "/admin/login",
  adminDashboard: "/admin/dashboard",
  adminContacts: "/admin/contacts",
  adminOrders: "/admin/orders",
  adminShipments: "/admin/shipments",
  products: "/products",
  bulkOrders: "/bulk-orders",
  productDetail: (slug: string) => `/products/${slug}`,
  cart: "/cart",
  checkout: "/checkout",
  checkoutConfirmation: (orderNumber: string) => `/checkout/confirmation/${orderNumber}`,
  authLogin: "/auth/login",
  account: "/account",
  accountOrders: "/account/orders",
  accountOrderDetail: (orderNumber: string) => `/account/orders/${orderNumber}`,
  about: "/about",
  contact: "/contact",
  faq: "/faq",
  reviews: "/reviews",
  trackOrder: "/track-order",
} as const;
